# Generated by Django 4.1.6 on 2023-02-14 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPlato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaRestaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoría', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='clienteulima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=255)),
                ('imagen', models.URLField(max_length=300)),
                ('categoría', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.categoriarestaurante')),
            ],
        ),
        migrations.CreateModel(
            name='PlatoRegistrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=100)),
                ('cantidad', models.PositiveSmallIntegerField()),
                ('precio', models.FloatField()),
                ('codigo_verificación', models.CharField(max_length=10)),
                ('estado', models.CharField(choices=[('1', 'Confirmado'), ('2', 'En preparación'), ('3', 'Entregado')], max_length=20)),
                ('registrado', models.CharField(choices=[('1', 'Si'), ('2', 'No')], max_length=3)),
                ('categoría', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.categoriaplato')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.clienteulima')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.restaurante')),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('precio', models.FloatField()),
                ('descripción', models.TextField()),
                ('imagen', models.URLField(max_length=300)),
                ('categoría', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.categoriaplato')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.restaurante')),
            ],
        ),
        migrations.CreateModel(
            name='MostrarPlato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=255)),
                ('imagen', models.URLField(max_length=300)),
                ('precio', models.FloatField()),
                ('categoría', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.categoriaplato')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.restaurante')),
            ],
        ),
        migrations.AddField(
            model_name='categoriaplato',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.restaurante'),
        ),
    ]
