# Generated by Django 4.1.6 on 2023-02-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_restaurante_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='estado',
            field=models.CharField(choices=[('1', 'Abierto'), ('0', 'Cerrado')], default=1, max_length=1),
        ),
    ]
