# Generated by Django 4.1.6 on 2023-02-11 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_categorias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=255)),
                ('codigo', models.IntegerField(max_length=255)),
                ('precio', models.IntegerField(max_length=255)),
                ('cantidad', models.IntegerField(max_length=255)),
                ('estado', models.IntegerField(choices=[(1, 'Preparado'), (2, 'Transportado'), (3, 'Entregado')], max_length=1)),
                ('restaurantes', models.IntegerField(choices=[(1, 'Sabor y punto'), (2, 'Corralito'), (3, 'Sabores y mixturas')], max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='categorias',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], max_length=1),
        ),
        migrations.AlterField(
            model_name='categorias',
            name='restaurantes',
            field=models.IntegerField(choices=[(1, 'Sabor y punto'), (2, 'Corralito'), (3, 'Sabores y mixturas')], max_length=1),
        ),
    ]
