# Generated by Django 4.1.6 on 2023-02-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_recomendacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomendacion',
            name='texto',
            field=models.TextField(),
        ),
    ]
