# Generated by Django 4.1.6 on 2023-02-12 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_restaurant_address_restaurant_phone'),
        ('backend', '0004_pedidos_alter_categorias_estado_and_more'),
    ]

    operations = [
    ]
