# Generated by Django 4.1.6 on 2023-02-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_plato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=8)),
                ('password', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=50)),
                ('carrera', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
