# Generated by Django 4.1.6 on 2023-02-12 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_cliente_alter_pedidos_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ofertas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=8)),
                ('nombre', models.CharField(max_length=40)),
                ('precio', models.IntegerField()),
                ('restaurante', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='backend.restaurant')),
            ],
        ),
    ]
