# Generated by Django 4.1.6 on 2023-02-12 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_categoriaplato_categoriarestaurante_clienteulima_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriarestaurante',
            name='categoría',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='estado',
            field=models.CharField(choices=[('1', 'Confirmado'), ('2', 'En preparación'), ('3', 'Entregado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='restaurantes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.restaurante'),
        ),
        migrations.AlterField(
            model_name='plato',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='platoregistrado',
            name='precio',
            field=models.FloatField(),
        ),
    ]
